# Generated by Django 3.2.13 on 2022-04-29 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Themes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(blank=True, default='Random', max_length=15, verbose_name='Тема')),
            ],
            options={
                'db_table': 'db_bP_themes',
            },
        ),
        migrations.CreateModel(
            name='ThemesToVerbalRiddles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('themes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Storage.themes')),
            ],
        ),
        migrations.CreateModel(
            name='VerbalRiddles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_publication', models.DateTimeField(auto_now_add=True, verbose_name='Дата появления')),
                ('is_published', models.BooleanField(default=True, verbose_name='Публичность')),
                ('question', models.TextField(blank=True, max_length=150, verbose_name='Вопрос')),
                ('answer', models.CharField(blank=True, max_length=20, verbose_name='Ответ')),
                ('themes', models.ManyToManyField(blank=True, through='Storage.ThemesToVerbalRiddles', to='Storage.Themes')),
            ],
            options={
                'verbose_name': 'словесные загадки',
                'verbose_name_plural': 'словесные загадки',
                'db_table': 'db_bP_verbal_riddles',
                'ordering': ['question', 'is_published', 'time_publication'],
            },
        ),
        migrations.AddField(
            model_name='themestoverbalriddles',
            name='vr',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Storage.verbalriddles'),
        ),
        migrations.CreateModel(
            name='Crossword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_publication', models.DateTimeField(auto_now_add=True, verbose_name='Дата появления')),
                ('is_published', models.BooleanField(default=True, verbose_name='Публичность')),
                ('title', models.CharField(blank=True, max_length=50, verbose_name='Заголовок')),
                ('likes', models.IntegerField(default=0, verbose_name='Лайки')),
                ('author', models.CharField(blank=True, default='LazzyPuzzle', max_length=30, verbose_name='Автор')),
                ('difficulty', models.CharField(blank=True, default='Normal', max_length=15, verbose_name='Сложность')),
                ('riddles', models.ManyToManyField(to='Storage.VerbalRiddles')),
                ('themes', models.ManyToManyField(to='Storage.Themes')),
            ],
            options={
                'verbose_name': 'кроссворды',
                'verbose_name_plural': 'кроссворды',
                'db_table': 'db_bP_crossword',
            },
        ),
    ]
