# Generated by Django 4.0.3 on 2022-03-24 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BasicSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_publication', models.DateTimeField(verbose_name='Дата появления')),
                ('is_published', models.BooleanField(default=True, verbose_name='Публичность')),
            ],
            options={
                'db_table': 'db_basic_setting',
            },
        ),
        migrations.CreateModel(
            name='Themes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(blank=True, default='Random', max_length=15, verbose_name='Тема')),
            ],
            options={
                'db_table': 'db_bP_themes',
            },
        ),
        migrations.CreateModel(
            name='VerbalRiddles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(blank=True, max_length=150, verbose_name='Вопрос')),
                ('answer', models.CharField(blank=True, max_length=20, verbose_name='Ответ')),
                ('basic_settings', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Storage.basicsettings')),
                ('themes', models.ManyToManyField(to='Storage.themes')),
            ],
            options={
                'verbose_name': 'словесные загадки',
                'verbose_name_plural': 'словесные загадки',
                'db_table': 'db_bP_verbal_riddles',
                'ordering': ['question', 'basic_settings'],
            },
        ),
        migrations.CreateModel(
            name='Puzzle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50, verbose_name='Заголовок')),
                ('likes', models.IntegerField(default=0, verbose_name='Лайки')),
                ('author', models.CharField(blank=True, default='LazzyPuzzle', max_length=30, verbose_name='Автор')),
                ('difficulty', models.CharField(blank=True, default='Normal', max_length=15, verbose_name='Сложность')),
                ('basic_settings', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Storage.basicsettings')),
            ],
            options={
                'verbose_name': 'базовые пазлы',
                'verbose_name_plural': 'базовые пазлы',
                'db_table': 'db_basicPuzzle',
                'ordering': ['author', 'likes', 'basic_settings'],
            },
        ),
        migrations.CreateModel(
            name='Crossword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Storage.puzzle')),
                ('riddles', models.ManyToManyField(to='Storage.verbalriddles')),
                ('themes', models.ManyToManyField(to='Storage.themes')),
            ],
            options={
                'verbose_name': 'базовые пазлы',
                'verbose_name_plural': 'базовые пазлы',
                'db_table': 'db_bP_crossword',
                'ordering': ['info'],
            },
        ),
    ]
