# Generated by Django 3.2.13 on 2022-04-15 16:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Storage', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='puzzle',
            name='basic_settings',
        ),
        migrations.AlterModelOptions(
            name='crossword',
            options={'verbose_name': 'кроссворды', 'verbose_name_plural': 'кроссворды'},
        ),
        migrations.AlterModelOptions(
            name='verbalriddles',
            options={'ordering': ['question', 'is_published', 'time_publication'], 'verbose_name': 'словесные загадки', 'verbose_name_plural': 'словесные загадки'},
        ),
        migrations.RemoveField(
            model_name='crossword',
            name='info',
        ),
        migrations.RemoveField(
            model_name='verbalriddles',
            name='basic_settings',
        ),
        migrations.AddField(
            model_name='crossword',
            name='author',
            field=models.CharField(blank=True, default='LazzyPuzzle', max_length=30, verbose_name='Автор'),
        ),
        migrations.AddField(
            model_name='crossword',
            name='difficulty',
            field=models.CharField(blank=True, default='Normal', max_length=15, verbose_name='Сложность'),
        ),
        migrations.AddField(
            model_name='crossword',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='Публичность'),
        ),
        migrations.AddField(
            model_name='crossword',
            name='likes',
            field=models.IntegerField(default=0, verbose_name='Лайки'),
        ),
        migrations.AddField(
            model_name='crossword',
            name='time_publication',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата появления'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='crossword',
            name='title',
            field=models.CharField(blank=True, max_length=50, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='verbalriddles',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='Публичность'),
        ),
        migrations.AddField(
            model_name='verbalriddles',
            name='time_publication',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата появления'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='BasicSettings',
        ),
        migrations.DeleteModel(
            name='Puzzle',
        ),
    ]
