# Generated by Django 3.2.13 on 2022-04-29 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Storage', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='themestoverbalriddles',
            table='db_bP_themes_to_vr',
        ),
    ]
