# Generated by Django 3.2.13 on 2022-04-29 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Storage', '0002_alter_themestoverbalriddles_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='themestoverbalriddles',
            name='themes',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Storage.themes'),
        ),
        migrations.AlterField(
            model_name='themestoverbalriddles',
            name='vr',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Storage.verbalriddles'),
        ),
        migrations.AlterField(
            model_name='verbalriddles',
            name='themes',
            field=models.ManyToManyField(blank=True, null=True, through='Storage.ThemesToVerbalRiddles', to='Storage.Themes'),
        ),
    ]
